-- MySQL Script generated by MySQL Workbench
-- 05/18/17 16:49:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema comeniusdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `comeniusdb` ;

-- -----------------------------------------------------
-- Schema comeniusdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comeniusdb` DEFAULT CHARACTER SET utf8 ;
USE `comeniusdb` ;

-- -----------------------------------------------------
-- Table `comeniusdb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`endereco` (
  `idendereco` INT NOT NULL,
  `logradouro` VARCHAR(100) NULL,
  `num` INT NULL,
  `bairro` VARCHAR(100) NULL,
  `complemento` VARCHAR(30) NULL,
  `cep` INT NULL,
  `codCidade` INT NULL,
  `uf` VARCHAR(2) NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `enderecoid` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `datanasc` DATE NULL,
  `senha` VARCHAR(45) NULL,
  `genero` CHAR(1) NULL,
  `estadoCivil` INT NULL,
  `nacionalidade` VARCHAR(45) NULL,
  `naturalidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_endereco_idx` (`enderecoid` ASC),
  CONSTRAINT `fk_usuario_endereco`
    FOREIGN KEY (`enderecoid`)
    REFERENCES `comeniusdb`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`telefone` (
  `idtelefone` INT NOT NULL,
  `usuarioid` INT NOT NULL,
  `tipo` INT NULL,
  `numero` INT NULL,
  `ramal` INT NULL,
  PRIMARY KEY (`idtelefone`),
  INDEX `fk_telefone_usuario1_idx` (`usuarioid` ASC),
  CONSTRAINT `fk_telefone_usuario1`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `comeniusdb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`funcionario` (
  `funcionarioid` INT NOT NULL,
  `funcao` VARCHAR(45) NULL,
  `numctps` INT NULL,
  `pis` INT NULL,
  `turno` INT NULL,
  `datainiciocontrato` DATE NULL,
  `datafimcontrato` DATE NULL,
  `cargahorariasemanal` INT NULL,
  PRIMARY KEY (`funcionarioid`),
  INDEX `fk_funcionario_usuario1_idx` (`funcionarioid` ASC),
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`funcionarioid`)
    REFERENCES `comeniusdb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`professor` (
  `professorid` INT NOT NULL,
  INDEX `fk_professor_funcionario1_idx` (`professorid` ASC),
  PRIMARY KEY (`professorid`),
  CONSTRAINT `fk_professor_funcionario1`
    FOREIGN KEY (`professorid`)
    REFERENCES `comeniusdb`.`funcionario` (`funcionarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`curriculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`curriculo` (
  `idcurriculo` INT NOT NULL,
  `serie` INT NULL,
  `ensino` VARCHAR(45) NULL,
  `chtotal` VARCHAR(45) NULL,
  PRIMARY KEY (`idcurriculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`turma` (
  `idturma` INT NOT NULL,
  `curriculoid` INT NOT NULL,
  `sala` VARCHAR(5) NULL,
  `turno` INT NULL,
  PRIMARY KEY (`idturma`),
  INDEX `fk_turma_curriculo1_idx` (`curriculoid` ASC),
  CONSTRAINT `fk_turma_curriculo1`
    FOREIGN KEY (`curriculoid`)
    REFERENCES `comeniusdb`.`curriculo` (`idcurriculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`aluno` (
  `alunoid` INT NOT NULL,
  `turmaid` INT NOT NULL,
  INDEX `fk_aluno_usuario1_idx` (`alunoid` ASC),
  PRIMARY KEY (`alunoid`),
  UNIQUE INDEX `usuarioid_UNIQUE` (`alunoid` ASC),
  INDEX `fk_aluno_turma1_idx` (`turmaid` ASC),
  CONSTRAINT `fk_aluno_usuario1`
    FOREIGN KEY (`alunoid`)
    REFERENCES `comeniusdb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`turmaid`)
    REFERENCES `comeniusdb`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`responsavel` (
  `responsavelid` INT NOT NULL,
  `empresa` VARCHAR(100) NULL,
  `profissao` VARCHAR(100) NULL,
  `grauinstrucao` INT NULL,
  INDEX `fk_responsavel_usuario1_idx` (`responsavelid` ASC),
  PRIMARY KEY (`responsavelid`),
  UNIQUE INDEX `responsavelid_UNIQUE` (`responsavelid` ASC),
  CONSTRAINT `fk_responsavel_usuario1`
    FOREIGN KEY (`responsavelid`)
    REFERENCES `comeniusdb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`alunoresponsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`alunoresponsavel` (
  `alunoid` INT NOT NULL,
  `responsavelid` INT NOT NULL,
  PRIMARY KEY (`alunoid`, `responsavelid`),
  INDEX `fk_aluno_has_responsavel_responsavel1_idx` (`responsavelid` ASC),
  INDEX `fk_aluno_has_responsavel_aluno1_idx` (`alunoid` ASC),
  CONSTRAINT `fk_aluno_has_responsavel_aluno1`
    FOREIGN KEY (`alunoid`)
    REFERENCES `comeniusdb`.`aluno` (`alunoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_responsavel_responsavel1`
    FOREIGN KEY (`responsavelid`)
    REFERENCES `comeniusdb`.`responsavel` (`responsavelid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`alunodisciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`alunodisciplina` (
  `alunoid` INT NOT NULL,
  `iddisciplina` INT NOT NULL,
  PRIMARY KEY (`alunoid`, `iddisciplina`),
  INDEX `fk_aluno_has_disciplina_aluno1_idx` (`alunoid` ASC),
  CONSTRAINT `fk_aluno_has_disciplina_aluno1`
    FOREIGN KEY (`alunoid`)
    REFERENCES `comeniusdb`.`aluno` (`alunoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`disciplina` (
  `iddisciplina` INT NOT NULL,
  `curriculoid` INT NOT NULL,
  `ch` INT NULL,
  `ementa` LONGTEXT NULL,
  PRIMARY KEY (`iddisciplina`, `curriculoid`),
  INDEX `fk_disciplina_has_curriculo_curriculo1_idx` (`curriculoid` ASC),
  CONSTRAINT `fk_disciplina_has_curriculo_curriculo1`
    FOREIGN KEY (`curriculoid`)
    REFERENCES `comeniusdb`.`curriculo` (`idcurriculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`avaliacao` (
  `idavaliacao` INT NOT NULL,
  `alunoid` INT NOT NULL,
  `disciplinaid` INT NOT NULL,
  `nota` DECIMAL NULL,
  `conceito` VARCHAR(5) NULL,
  `data` DATE NULL,
  PRIMARY KEY (`idavaliacao`),
  INDEX `fk_avaliacao_aluno1_idx` (`alunoid` ASC),
  INDEX `fk_avaliacao_disciplina1_idx` (`disciplinaid` ASC),
  CONSTRAINT `fk_avaliacao_aluno1`
    FOREIGN KEY (`alunoid`)
    REFERENCES `comeniusdb`.`aluno` (`alunoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_disciplina1`
    FOREIGN KEY (`disciplinaid`)
    REFERENCES `comeniusdb`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`mensalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`mensalidade` (
  `idmensalidade` INT NOT NULL,
  `alunoid` INT NOT NULL,
  PRIMARY KEY (`idmensalidade`),
  INDEX `fk_mensalidade_aluno1_idx` (`alunoid` ASC),
  CONSTRAINT `fk_mensalidade_aluno1`
    FOREIGN KEY (`alunoid`)
    REFERENCES `comeniusdb`.`aluno` (`alunoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`certidao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`certidao` (
  `usuarioid` INT NOT NULL,
  `numero` INT NULL,
  `fls` VARCHAR(10) NULL,
  `livro` VARCHAR(10) NULL,
  `cartorio` VARCHAR(100) NULL,
  `dataemissao` DATE NULL,
  INDEX `fk_certidao_usuario1_idx` (`usuarioid` ASC),
  PRIMARY KEY (`usuarioid`),
  CONSTRAINT `fk_certidao_usuario1`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `comeniusdb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`documentos` (
  `usuarioid` INT NOT NULL,
  `numrg` INT NULL,
  `orgaoemissorrg` VARCHAR(100) NULL,
  `ufrg` VARCHAR(2) NULL,
  `dataemissaorg` DATE NULL,
  `cpf` INT(11) NULL,
  PRIMARY KEY (`usuarioid`),
  INDEX `fk_documentos_usuario1_idx` (`usuarioid` ASC),
  CONSTRAINT `fk_documentos_usuario1`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `comeniusdb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`formacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`formacao` (
  `idformacao` INT NOT NULL,
  `funcionarioid` INT NOT NULL,
  `curso` VARCHAR(100) NULL,
  `instituicao` VARCHAR(150) NULL,
  `anoinicio` INT NULL,
  `anoconclusao` INT NULL,
  `tipograduacao` INT NULL,
  PRIMARY KEY (`idformacao`),
  INDEX `fk_formacao_funcionario1_idx` (`funcionarioid` ASC),
  CONSTRAINT `fk_formacao_funcionario1`
    FOREIGN KEY (`funcionarioid`)
    REFERENCES `comeniusdb`.`funcionario` (`funcionarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`professordisciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`professordisciplina` (
  `professorid` INT NOT NULL,
  `iddisciplina` INT NOT NULL,
  `curriculoid` INT NOT NULL,
  PRIMARY KEY (`professorid`, `iddisciplina`, `curriculoid`),
  INDEX `fk_professor_has_disciplina_disciplina1_idx` (`iddisciplina` ASC, `curriculoid` ASC),
  INDEX `fk_professor_has_disciplina_professor1_idx` (`professorid` ASC),
  CONSTRAINT `fk_professor_has_disciplina_professor1`
    FOREIGN KEY (`professorid`)
    REFERENCES `comeniusdb`.`professor` (`professorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_disciplina_disciplina1`
    FOREIGN KEY (`iddisciplina` , `curriculoid`)
    REFERENCES `comeniusdb`.`disciplina` (`iddisciplina` , `curriculoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`professorturma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`professorturma` (
  `professorid` INT NOT NULL,
  `turmaid` INT NOT NULL,
  `disciplinaid` INT NOT NULL,
  `curriculoid` INT NOT NULL,
  PRIMARY KEY (`professorid`, `turmaid`),
  INDEX `fk_professor_has_turma_turma2_idx` (`turmaid` ASC),
  INDEX `fk_professor_has_turma_professor1_idx` (`professorid` ASC),
  INDEX `fk_professorturma_disciplina1_idx` (`disciplinaid` ASC, `curriculoid` ASC),
  CONSTRAINT `fk_professor_has_turma_professor1`
    FOREIGN KEY (`professorid`)
    REFERENCES `comeniusdb`.`professor` (`professorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_turma_turma2`
    FOREIGN KEY (`turmaid`)
    REFERENCES `comeniusdb`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professorturma_disciplina1`
    FOREIGN KEY (`disciplinaid` , `curriculoid`)
    REFERENCES `comeniusdb`.`disciplina` (`iddisciplina` , `curriculoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`presenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`presenca` (
  `idpresenca` INT NOT NULL,
  `alunoid` INT NOT NULL,
  `disciplinaid` INT NOT NULL,
  `presenca` TINYINT(1) NULL,
  `data` DATE NULL,
  PRIMARY KEY (`idpresenca`),
  INDEX `fk_presenca_aluno1_idx` (`alunoid` ASC),
  INDEX `fk_presenca_disciplina1_idx` (`disciplinaid` ASC),
  CONSTRAINT `fk_presenca_aluno1`
    FOREIGN KEY (`alunoid`)
    REFERENCES `comeniusdb`.`aluno` (`alunoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presenca_disciplina1`
    FOREIGN KEY (`disciplinaid`)
    REFERENCES `comeniusdb`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comeniusdb`.`boletim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comeniusdb`.`boletim` (
  `idboletim` INT NOT NULL,
  `alunoid` INT NOT NULL,
  `disciplinaid` INT NOT NULL,
  `curriculoid` INT NOT NULL,
  `nota` INT NULL,
  `faltas` INT NULL,
  `periodo` INT NULL,
  `conceito` CHAR(1) NULL,
  PRIMARY KEY (`idboletim`),
  INDEX `fk_boletim_aluno1_idx` (`alunoid` ASC),
  INDEX `fk_boletim_disciplina1_idx` (`disciplinaid` ASC, `curriculoid` ASC),
  CONSTRAINT `fk_boletim_aluno1`
    FOREIGN KEY (`alunoid`)
    REFERENCES `comeniusdb`.`aluno` (`alunoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boletim_disciplina1`
    FOREIGN KEY (`disciplinaid` , `curriculoid`)
    REFERENCES `comeniusdb`.`disciplina` (`iddisciplina` , `curriculoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
