-- MySQL Script generated by MySQL Workbench
-- 08/11/16 18:59:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema comenius
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comenius
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comenius` DEFAULT CHARACTER SET utf8 ;
USE `comenius` ;

-- -----------------------------------------------------
-- Table `comenius`.`uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`uf` (
  `sigla` VARCHAR(2) NOT NULL,
  `nome` VARCHAR(30) NULL,
  PRIMARY KEY (`sigla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`cidade` (
  `idcidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `uf_sigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idcidade`),
  INDEX `fk_cidade_uf1_idx` (`uf_sigla` ASC),
  CONSTRAINT `fk_cidade_uf1`
    FOREIGN KEY (`uf_sigla`)
    REFERENCES `comenius`.`uf` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(50) NULL,
  `num` INT NULL,
  `bairro` VARCHAR(45) NULL,
  `complemento` VARCHAR(30) NULL,
  `cep` INT NULL,
  `cidade_idcidade` INT NOT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_endereco_cidade1_idx` (`cidade_idcidade` ASC),
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`cidade_idcidade`)
    REFERENCES `comenius`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idendereco` INT NOT NULL,
  `nome` VARCHAR(80) NULL,
  `email` VARCHAR(45) NULL,
  `datanasc` DATE NULL,
  `rg` VARCHAR(20) NULL,
  `rgemissor` VARCHAR(10) NULL,
  `ufrg` VARCHAR(2) NOT NULL,
  `senha` VARCHAR(45) NULL,
  `cpf` BIGINT(11) NULL,
  `genero` INT NULL,
  `estadoCivil` VARCHAR(15) NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_endereco1_idx` (`idendereco` ASC),
  INDEX `fk_usuario_uf1_idx` (`ufrg` ASC),
  CONSTRAINT `fk_usuario_endereco1`
    FOREIGN KEY (`idendereco`)
    REFERENCES `comenius`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_uf1`
    FOREIGN KEY (`ufrg`)
    REFERENCES `comenius`.`uf` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`turma` (
  `idturma` INT NOT NULL,
  `serie` INT NULL,
  `turno` INT NULL,
  `ensino` VARCHAR(45) NULL,
  PRIMARY KEY (`idturma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`aluno` (
  `idaluno` INT NOT NULL,
  `idturma` INT NOT NULL,
  `cgm` INT NULL,
  `nacionalidade` VARCHAR(45) NULL,
  `naturalidade` VARCHAR(45) NULL,
  `cnnum` INT NULL,
  `cnfls` INT NULL,
  `cnlivro` VARCHAR(10) NULL,
  `cncartorio` VARCHAR(45) NULL,
  INDEX `fk_aluno_usuario1_idx` (`idaluno` ASC),
  INDEX `fk_aluno_turma1_idx` (`idturma` ASC),
  PRIMARY KEY (`idaluno`),
  CONSTRAINT `fk_aluno_usuario1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `comenius`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`idturma`)
    REFERENCES `comenius`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `comenius`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`professor` (
  `idprof` INT NOT NULL,
  INDEX `fk_professor_usuario1_idx` (`idprof` ASC),
  PRIMARY KEY (`idprof`),
  CONSTRAINT `fk_professor_usuario1`
    FOREIGN KEY (`idprof`)
    REFERENCES `comenius`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`prof_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`prof_turma` (
  `idprof` INT NOT NULL,
  `idturma` INT NOT NULL,
  PRIMARY KEY (`idprof`, `idturma`),
  INDEX `fk_professor_has_turma_turma1_idx` (`idturma` ASC),
  INDEX `fk_professor_has_turma_professor1_idx` (`idprof` ASC),
  CONSTRAINT `fk_professor_has_turma_professor1`
    FOREIGN KEY (`idprof`)
    REFERENCES `comenius`.`professor` (`idprof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_turma_turma1`
    FOREIGN KEY (`idturma`)
    REFERENCES `comenius`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`disciplina` (
  `iddisciplina` INT NOT NULL,
  `ementa` LONGTEXT NULL,
  `ch` INT NULL,
  `prof_turma_idprof` INT NOT NULL,
  `prof_turma_idturma` INT NOT NULL,
  PRIMARY KEY (`iddisciplina`),
  INDEX `fk_disciplina_prof_turma1_idx` (`prof_turma_idprof` ASC, `prof_turma_idturma` ASC),
  CONSTRAINT `fk_disciplina_prof_turma1`
    FOREIGN KEY (`prof_turma_idprof` , `prof_turma_idturma`)
    REFERENCES `comenius`.`prof_turma` (`idprof` , `idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`professor_has_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`professor_has_disciplina` (
  `professor_usuario_idusuario` INT NOT NULL,
  `disciplina_iddisciplina` INT NOT NULL,
  PRIMARY KEY (`professor_usuario_idusuario`, `disciplina_iddisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`matricula` (
  `idmatricula` INT NOT NULL,
  `idaluno` INT NOT NULL,
  `idturma` INT NOT NULL,
  `ensino` VARCHAR(45) NULL,
  `origem` VARCHAR(100) NULL,
  PRIMARY KEY (`idmatricula`),
  INDEX `fk_matricula_aluno1_idx` (`idaluno` ASC),
  INDEX `fk_matricula_turma1_idx` (`idturma` ASC),
  CONSTRAINT `fk_matricula_aluno1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `comenius`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_turma1`
    FOREIGN KEY (`idturma`)
    REFERENCES `comenius`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`avaliacao` (
  `idavaliacao` INT NOT NULL,
  `idmatricula` INT NOT NULL,
  `iddisciplina` INT NOT NULL,
  `periodo` VARCHAR(15) NULL,
  `nota` DECIMAL NULL,
  `faltas` INT NULL,
  PRIMARY KEY (`idavaliacao`),
  INDEX `fk_avaliacao_matricula1_idx` (`idmatricula` ASC),
  INDEX `fk_avaliacao_disciplina1_idx` (`iddisciplina` ASC),
  CONSTRAINT `fk_avaliacao_matricula1`
    FOREIGN KEY (`idmatricula`)
    REFERENCES `comenius`.`matricula` (`idmatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_disciplina1`
    FOREIGN KEY (`iddisciplina`)
    REFERENCES `comenius`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`Funcionario` (
  `idusuario` INT NOT NULL,
  `funcao` INT NULL,
  `formacao` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NULL,
  `instituicao` VARCHAR(45) NULL,
  `anoInicio` INT NULL,
  `anoFinal` INT NULL,
  `numCartTrab` INT NULL,
  `pis` INT NULL,
  `periodoTrabalho` INT NULL,
  `inicioContrato` DATE NULL,
  INDEX `fk_Funcionario_usuario_idx` (`idusuario` ASC),
  PRIMARY KEY (`idusuario`),
  CONSTRAINT `fk_Funcionario_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `comenius`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`Mensalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`Mensalidade` (
  `idMensalidade` INT NOT NULL,
  `vencimento` DATE NULL,
  `situacao` INT NULL,
  `lanche` INT NULL,
  `idaluno` INT NOT NULL,
  PRIMARY KEY (`idMensalidade`),
  INDEX `fk_Mensalidade_aluno1_idx` (`idaluno` ASC),
  CONSTRAINT `fk_Mensalidade_aluno1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `comenius`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`pagamento` (
  `idpagamento` INT NOT NULL,
  `banco` VARCHAR(45) NULL,
  `ag` VARCHAR(45) NULL,
  `conta` VARCHAR(45) NULL,
  `tipoconta` VARCHAR(45) NULL,
  `valorsalariobruto` DECIMAL NULL,
  `descontos` DECIMAL NULL,
  `Funcionario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idpagamento`),
  INDEX `fk_pagamento_Funcionario1_idx` (`Funcionario_idusuario` ASC),
  CONSTRAINT `fk_pagamento_Funcionario1`
    FOREIGN KEY (`Funcionario_idusuario`)
    REFERENCES `comenius`.`Funcionario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`responsavel` (
  `idresponsavel` INT NOT NULL,
  `nome` VARCHAR(60) NULL,
  `datanasc` DATE NULL,
  `nacionalidade` VARCHAR(45) NULL,
  `rg` VARCHAR(20) NULL,
  `emissorrg` VARCHAR(10) NULL,
  `rguf` VARCHAR(2) NOT NULL,
  `cpf` INT NULL,
  `empresatrab` VARCHAR(60) NULL,
  `profissao` VARCHAR(45) NULL,
  `fonecomercial` INT NULL,
  `celular` INT NULL,
  PRIMARY KEY (`idresponsavel`),
  INDEX `fk_responsavel_uf1_idx` (`rguf` ASC),
  CONSTRAINT `fk_responsavel_uf1`
    FOREIGN KEY (`rguf`)
    REFERENCES `comenius`.`uf` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`resp_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`resp_aluno` (
  `idresponsavel` INT NOT NULL,
  `idaluno` INT NOT NULL,
  PRIMARY KEY (`idresponsavel`, `idaluno`),
  INDEX `fk_responsavel_has_aluno_aluno1_idx` (`idaluno` ASC),
  INDEX `fk_responsavel_has_aluno_responsavel1_idx` (`idresponsavel` ASC),
  CONSTRAINT `fk_responsavel_has_aluno_responsavel1`
    FOREIGN KEY (`idresponsavel`)
    REFERENCES `comenius`.`responsavel` (`idresponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responsavel_has_aluno_aluno1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `comenius`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comenius`.`prof_discip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`prof_discip` (
  `idprof` INT NOT NULL,
  `iddisciplina` INT NOT NULL,
  PRIMARY KEY (`idprof`, `iddisciplina`),
  INDEX `fk_professor_has_disciplina1_disciplina1_idx` (`iddisciplina` ASC),
  INDEX `fk_professor_has_disciplina1_professor1_idx` (`idprof` ASC),
  CONSTRAINT `fk_professor_has_disciplina1_professor1`
    FOREIGN KEY (`idprof`)
    REFERENCES `comenius`.`professor` (`idprof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_disciplina1_disciplina1`
    FOREIGN KEY (`iddisciplina`)
    REFERENCES `comenius`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `comenius` ;

-- -----------------------------------------------------
-- Placeholder table for view `comenius`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comenius`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `comenius`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comenius`.`view1`;
USE `comenius`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
